//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHangGiaySABO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-PH354HUY\\SQLSEVER;Initial Catalog=QLCUAHANGGIAY;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string QLCUAHANGGIAYConnectionString {
            get {
                return ((string)(this["QLCUAHANGGIAYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-PH354HUY\\SQLSEVER;Initial Catalog=QLSHOPGIAY;Integrated Securi" +
            "ty=True;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string QLSHOPGIAYConnectionString {
            get {
                return ((string)(this["QLSHOPGIAYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-MIJ87KT\\DINHCHUONG;Initial Catalog=QLSHOPGIAY;Integrated Secu" +
            "rity=True")]
        public string QLSHOPGIAYConnectionString1 {
            get {
                return ((string)(this["QLSHOPGIAYConnectionString1"]));
            }
        }
    }
}
